### ISSUE TITLE
[Blocker][EI 6.1] Cannot run ciphertool.sh for secure vault configurations

### ISSUE THREAD

**Issue by ushanib** [wso2/product-ei#302]
sh ciphertool.sh -Dconfigure
ciphertool.sh: line 127: /home/ushani/Software/jdk1.8.0_60/bin/java: Argument list too long.

JDK 1.7, 1.8 Both have the issue
Env : Fedora 23
Standalone pack 16-3-2017 pack

**Comment by nandika** [comment]
This is now fixed. ciphertool.sh should be run from  CARBON_HOME

**Comment by ushanib** [comment]
Tested in Alpha pack. Still have issue. It says cipher-standalone-config.properties does not exist.

ciphertool.sh -Dconfigure
```
Exception in thread "main" org.wso2.ciphertool.exception.CipherToolException: File, cipher-standalone-config.properties does not exist.
	at org.wso2.ciphertool.utils.Utils.setSystemProperties(Utils.java:247)
	at org.wso2.ciphertool.CipherTool.initialize(CipherTool.java:93)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:52)
```

**Comment by ushanib** [comment]
When you consider usability, it should allow to run the script from anywhere just by providing the path

**Comment by nandika** [comment]
https://github.com/wso2/product-ei/pull/430

**Comment by nandika** [comment]
Documentation updated to mention that cipertool should be run from product profile home and not from bin directory
